---

# download Url csf
csf_url: "https://download.configserver.com/csf.tgz"

# Allow incoming TCP ports
TCP_IN: "20,21,22,25,53,80,110,143,443,465,587,993,995"

# Allow outgoing TCP ports
TCP_OUT:  "20,21,22,25,53,80,110,113,443,587,993,995"

# Allow incoming UDP ports
UDP_IN: "20,21,53,80,443"

# To allow outgoing traceroute add 33434:33523 to this list
UDP_OUT: "20,21,53,113,123"

# Allow incoming PING. Disabling PING will likely break external uptime
ICMP_IN: "1"

# ipv6 enable 1 disable 0
IPV6: "0"

# These changes are not necessary if the SPI firewall is used
IPV6_SPI: "1"

# Allow incoming IPv6 TCP ports
TCP6_IN: "20,21,22,25,53,80,110,143,443,465,587,993,995"

# Allow outgoing IPv6 TCP ports
TCP6_OUT: "20,21,22,25,53,80,110,113,443,587,993,995"

# Allow incoming IPv6 UDP ports
UDP6_IN: "20,21,53,80,443"

# Allow outgoing IPv6 UDP ports
# To allow outgoing traceroute add 33434:33523 to this list

UDP6_OUT: "20,21,53,113,123"
